### ISSUE TITLE
weird resizing of config window

### ISSUE THREAD

**Issue by jappyjan** [fshutdown/JMeter-WebSocketSampler#83]
I'm using JMeter on MacOs using Homebrew and installed this plugin via the plugin-manager.
When adding a WebSocketSampler to my LoopController and opening the config window of that sampler, the window resizes it self and starts to "grow"...
it gets larger and larger without me doing anything...

![Bildschirmvideo-aufnehmen-2020-05-27-um-10 18 59](https://user-images.githubusercontent.com/10154260/82995374-ccd3cc80-a003-11ea-8f96-f08a8b964cc6.gif)

**Comment by quyeny2k** [comment]
I am having the same issue.

**Comment by AdrianBathurst** [comment]
I'm having the same issue, on Windows 10.

**Comment by ShuiPingYang** [comment]
me too , it becomes longer and longer and not stop
